import type { Metadata } from 'next';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import './globals.css';
import ReactQueryProvider from '@/components/wrappers/ReactQueryProvider';
import MainLayout from '@/components/wrappers/Layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="pt-BR">
      <body className={`antialiased`}>
        <ReactQueryProvider>
          <AntdRegistry>
            <MainLayout>{children}</MainLayout>
          </AntdRegistry>
        </ReactQueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;

